import type {
  ScenarioDefinition,
  Workload,
  Preferences,
  Constraints,
} from "./types";
import {
  defaultWorkload,
  defaultConstraints,
  balanced,
} from "../data/defaults";
const make = (
  id: string,
  title: ScenarioDefinition["title"],
  description: ScenarioDefinition["description"],
  workload: Partial<Workload>,
  preferences: Partial<Preferences> = {},
  constraints: Partial<Constraints> = {},
): ScenarioDefinition => ({
  id,
  title,
  description,
  workload: { ...defaultWorkload, ...workload },
  preferences: { ...balanced, ...preferences },
  constraints: { ...defaultConstraints, ...constraints },
  learningObjectives: description,
});
export const scenarios: ScenarioDefinition[] = [
  make(
    "team70",
    ["70B team", "70B ekibi"],
    [
      "Where should this 70B model run? Size for 20 peak requests; price the average load.",
      "Bu 70B model nerede çalışmalı? Kapasiteyi 20 tepe isteğe, maliyeti ortalama yüke göre inceleyin.",
    ],
    {},
  ),
  make(
    "personal",
    ["Personal developer", "Bireysel geliştirici"],
    [
      "Sparse coding workloads can leave purchased capacity idle.",
      "Seyrek kodlama iş yükleri satın alınan kapasiteyi boşta bırakabilir.",
    ],
    {
      concurrency: 1,
      peakConcurrency: 1,
      hoursPerDay: 3,
      requestsPerDay: 80,
      utilization: 0.15,
      shape: "bursty",
      privacy: "medium",
      growth: "static",
      horizon: 12,
    },
    { cost: 60, privacy: 15, operations: 20, scale: 5 },
  ),
  make(
    "startup",
    ["API-first startup", "API ile başlayan girişim"],
    [
      "Start with little demand; inspect provider dependence as demand grows.",
      "Az taleple başlayın; talep büyürken sağlayıcı bağımlılığını inceleyin.",
    ],
    {
      parametersB: 8,
      layers: 32,
      context: 4096,
      maxContext: 8192,
      concurrency: 1,
      peakConcurrency: 4,
      requestsPerDay: 100,
      utilization: 0.1,
      privacy: "low",
      growth: "rapid",
      shape: "bursty",
      horizon: 12,
    },
    { cost: 45, privacy: 5, operations: 30, scale: 20 },
  ),
  make(
    "always",
    ["Always-on service", "Kesintisiz servis"],
    [
      "Stable high use changes ownership economics; one node still has no failover.",
      "Sürekli yüksek kullanım sahiplik maliyetini değiştirir; tek düğüm hâlâ yedeksizdir.",
    ],
    {
      hoursPerDay: 24,
      daysPerMonth: 30,
      utilization: 0.9,
      requestsPerDay: 12000,
      privacy: "high",
      shape: "continuous",
      growth: "static",
      availability: "always",
    },
    { cost: 50, privacy: 35, operations: 10, scale: 5 },
  ),
  make(
    "privacy",
    ["Privacy first", "Önce gizlilik"],
    [
      "Local processing is a hard boundary. External paths are ineligible.",
      "Yerel işleme kesin bir sınırdır. Harici seçenekler elenir.",
    ],
    { privacy: "local", growth: "static" },
    { cost: 45, privacy: 35, operations: 15, scale: 5 },
  ),
  make(
    "company",
    ["30-person company", "30 kişilik şirket"],
    [
      "Sensitive documents, 30 typical users and a 60-request peak challenge fixed capacity.",
      "Hassas belgeler, 30 tipik kullanıcı ve 60 istek tepe yükü sabit kapasiteyi zorlar.",
    ],
    {
      concurrency: 30,
      peakConcurrency: 60,
      context: 8192,
      maxContext: 8192,
      requestsPerDay: 6000,
      utilization: 0.7,
      privacy: "high",
      growth: "rapid",
    },
    { cost: 30, privacy: 25, operations: 25, scale: 20 },
    { exactModel: true },
  ),
  make(
    "batch",
    ["Bursty batch", "Aralıklı toplu iş"],
    [
      "Scheduled jobs may release rented capacity; startup time is not simulated.",
      "Zamanlanmış işler kiralık kapasiteyi serbest bırakabilir; başlatma süresi simüle edilmez.",
    ],
    {
      parametersB: 8,
      layers: 32,
      context: 4096,
      maxContext: 8192,
      concurrency: 2,
      peakConcurrency: 8,
      shape: "batch",
      ttft: "relaxed",
      hoursPerDay: 4,
      utilization: 0.3,
      privacy: "medium",
    },
  ),
];
